name: bitcoinsistemi
description: Eyüp Akkaya Bitcoin Sistemi

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  #  hexcolor: ^2.0.5
  flutter_html: ^2.2.1
  webview_flutter: ^2.0.4
  intl: ^0.17.0
  photo_view: ^0.13.0
  url_launcher: ^6.0.18
  search_page: ^2.0.0+1
  cached_network_image: ^3.2.0
  checkbox_grouped: ^1.7.1
  shared_preferences: ^2.0.12
  percent_indicator: ^4.0.0
  onesignal_flutter: ^3.2.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add asset to your application, add an asset section, like this:
  assets:
    - asset/bitcoinsistemi-logo.png
    - asset/default.png
    - asset/bitcoinsistem.png
    - asset/bitcoinsistemi-darkmode.png
    #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding asset from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
